# Generated by Django 2.1.7 on 2020-06-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcloudbridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackcredentials',
            name='os_project_domain_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
