# Generated by Django 2.2 on 2019-04-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcloudbridge', '0001_squashed_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpcredentials',
            name='vm_default_username',
            field=models.CharField(default='cbuser', max_length=100),
        ),
    ]
