# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcloudbridge', '0002_flatten_aws_cloud_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azure',
            name='resource_group',
        ),
        migrations.RemoveField(
            model_name='azure',
            name='storage_account',
        ),
        migrations.RemoveField(
            model_name='azure',
            name='vm_default_user_name',
        ),
        migrations.AddField(
            model_name='azurecredentials',
            name='resource_group',
            field=models.CharField(default='cloudbridge', max_length=64),
        ),
        migrations.AddField(
            model_name='azurecredentials',
            name='storage_account',
            field=models.CharField(default='cbstorage', max_length=24),
        ),
        migrations.AddField(
            model_name='azurecredentials',
            name='vm_default_username',
            field=models.CharField(default='cbuser', max_length=100),
        ),
    ]
