# Generated by Django 2.1.7 on 2019-04-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcloudbridge', '0002_gcpcredentials_vm_default_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awscredentials',
            old_name='access_key',
            new_name='aws_access_key',
        ),
        migrations.RenameField(
            model_name='awscredentials',
            old_name='secret_key',
            new_name='aws_secret_key',
        ),
        migrations.RenameField(
            model_name='azurecredentials',
            old_name='client_id',
            new_name='azure_client_id',
        ),
        migrations.RenameField(
            model_name='azurecredentials',
            old_name='resource_group',
            new_name='azure_resource_group',
        ),
        migrations.RenameField(
            model_name='azurecredentials',
            old_name='secret',
            new_name='azure_secret',
        ),
        migrations.RenameField(
            model_name='azurecredentials',
            old_name='storage_account',
            new_name='azure_storage_account',
        ),
        migrations.RenameField(
            model_name='azurecredentials',
            old_name='subscription_id',
            new_name='azure_subscription_id',
        ),
        migrations.RenameField(
            model_name='azurecredentials',
            old_name='tenant',
            new_name='azure_tenant',
        ),
        migrations.RenameField(
            model_name='azurecredentials',
            old_name='vm_default_username',
            new_name='azure_vm_default_username',
        ),
        migrations.RenameField(
            model_name='gcpcredentials',
            old_name='vm_default_username',
            new_name='gcp_vm_default_username',
        ),
        migrations.RenameField(
            model_name='openstackcredentials',
            old_name='password',
            new_name='os_password',
        ),
        migrations.RenameField(
            model_name='openstackcredentials',
            old_name='project_domain_name',
            new_name='os_project_domain_name',
        ),
        migrations.RenameField(
            model_name='openstackcredentials',
            old_name='project_name',
            new_name='os_project_name',
        ),
        migrations.RenameField(
            model_name='openstackcredentials',
            old_name='user_domain_name',
            new_name='os_user_domain_name',
        ),
        migrations.RenameField(
            model_name='openstackcredentials',
            old_name='username',
            new_name='os_username',
        ),
    ]
