# Generated by Django 3.2.9 on 2022-06-20 18:38

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djcloudbridge', '0002_openstackcredentials_os_project_domain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstackcredentials',
            name='os_application_credential_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openstackcredentials',
            name='os_application_credential_secret',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='openstackcredentials',
            name='os_password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='openstackcredentials',
            name='os_project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='openstackcredentials',
            name='os_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
