# Generated by Django 2.1.3 on 2019-02-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcloudbridge', '0004_migrate_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GCE',
            new_name='GCP',
        ),
        migrations.RenameModel(
            old_name='GCECredentials',
            new_name='GCPCredentials',
        ),
        migrations.AlterModelOptions(
            name='gcp',
            options={'verbose_name': 'GCP', 'verbose_name_plural': 'GCP'},
        ),
        migrations.AlterModelOptions(
            name='gcpcredentials',
            options={'verbose_name': 'GCP Credential', 'verbose_name_plural': 'GCP Credentials'},
        ),
    ]
