# Generated by Django 2.1.7 on 2019-11-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcloudbridge', '0004_rename_gcp_creds_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='cloudbridge_settings',
            field=models.TextField(blank=True, help_text='Extra settings to pass to the cloudbridge provider', max_length=16384, null=True),
        ),
    ]
