# Generated by Django 2.1.7 on 2019-03-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcloudbridge', '0006_decompose_cloud_and_add_zone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudOld',
        ),
    ]
